### ISSUE TITLE
You may be interested in SpaceVim

### ISSUE THREAD

**Issue by bLuka** [HugoKempfer/Vim_Dotfiles#1]
Hi Hugo,

You may already know it, but SpaceVim offers a fully-configurable vim distribution based on plugins synergies.

The layer system allows, for example, configure SpaceVim with a single line to a prepared Rust plugins package already pre-configured.

It's a bit more difficult to handle specific configuration (like switching main shortcuts for handling a different keyboard layout), but its “*layer*” approach seduced me 🙂

**Comment by HugoKempfer** [comment]
Hi @bLuka,

Thanks for opening this issue !
Concerning SpaceVim, I effectively know its existence and I even tried it for a short time.
It offers a very well done configuration modularity, and the layered combinated bindings are very intuitive (always according to the vim paradigm :slightly_smiling_face:).

However despite the very complete documentation, I didn't succeed to replace some plugins and bindings (for example I wanted to change de default linter/debugger in favor of ale).
At this time I was in a rush and just needed to get the job done, so I kept my minimal config.
I now realise that using such an environement is essential when you're working with more and more complex frameworks..
Plus the SV config is way more hackable than I thought!

But as you remind me about SV, I gonna re-try to configure it in order to make it my new home ! :+1:

**Comment by bLuka** [comment]
Seems there's a recent commit (end of 2017) you may be interested in :slightly_smiling_face: 
https://github.com/SpaceVim/SpaceVim/commit/0a6fb1b9a19d57f0c29a885f3bdb99d9eba7f9b6

**Comment by HugoKempfer** [comment]
> Seems there's a recent commit (end of 2017) you may be interested in 
> [SpaceVim/SpaceVim@0a6fb1b](https://github.com/SpaceVim/SpaceVim/commit/0a6fb1b9a19d57f0c29a885f3bdb99d9eba7f9b6)

Wow I missed it from the changelogs, thanks for sharing!
Plus as I said I switched back to SpaceVim :+1:
